# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  adcyberwatch-infra

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform: AWS::Serverless-2016-10-31

Parameters:
  CognitoDomainPrefix:
    Type: String
    Description: "Unique Cognito Hosted UI domain prefix (must be unique per region)"
    AllowedPattern: '^[a-z0-9-]{1,63}$'
    Default: poc-cyberwatch-ai
  CreateCognitoDomain:
    Type: String
    Default: "false"
    AllowedValues:
      - "true"
      - "false"
    Description: Set to "true" to create/manage the Cognito Hosted UI domain from this stack.

  TenantAlias:
    Type: String
    Default: ad-cyberwatch-ai
    Description: Tenant alias used for runtime config.
  UiCustomDomain:
    Type: String
    Default: https://ad-cyberwatch-ai.ouritres.com
    Description: Primary UI origin (CORS + Cognito callback).
  DefaultDataEnv:
    Type: String
    Default: prod
    Description: Default selected data environment.
  EnabledDataEnvs:
    Type: String
    Default: prod,dev
    Description: Comma-separated list of enabled environments.

Conditions:
  CreateDomainCondition:
    Fn::Equals:
      - !Ref CreateCognitoDomain
      - "true"

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

  # ----------------------------
  # S3 Buckets
  # ----------------------------
  RawBucket:
    Type: AWS::S3::Bucket
    Properties:
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: true
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true


  CuratedBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  FrameworksBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # ----------------------------
  # UI Hosting: S3 (private) + CloudFront OAI + Distribution
  # ----------------------------
  UiBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  UiCloudFrontOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub "${AWS::StackName} UI OAI"

  UiBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref UiBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowCloudFrontRead
            Effect: Allow
            Principal:
              CanonicalUser: !GetAtt UiCloudFrontOAI.S3CanonicalUserId
            Action:
              - s3:GetObject
            Resource: !Sub "${UiBucket.Arn}/*"

  UiDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        PriceClass: PriceClass_100
        DefaultRootObject: index.html
        Origins:
          - Id: UiS3Origin
            DomainName: !GetAtt UiBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${UiCloudFrontOAI}'
        DefaultCacheBehavior:
          TargetOriginId: UiS3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
          Compress: true
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
          MinimumProtocolVersion: TLSv1.2_2021

  # ----------------------------
  # DynamoDB (PAY_PER_REQUEST, pk/sk)
  # ----------------------------
  AdCyberwatchMainTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: adcyberwatch-main
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE

  # ----------------------------
  # Cognito (User Pool + SPA App Client)
  # ----------------------------
  AdCyberwatchUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub "${AWS::StackName}-userpool"
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email

  AdCyberwatchUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref AdCyberwatchUserPool
      ClientName: spa
      GenerateSecret: false
      PreventUserExistenceErrors: ENABLED
      # "SDK-based sign-in" (suffisant pour POC SPA sans Hosted UI)
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_ADMIN_USER_PASSWORD_AUTH
      # OAuth configuration for Hosted UI
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - email
        - openid
        - profile
      AllowedOAuthFlowsUserPoolClient: true
      EnableTokenRevocation: true
      CallbackURLs:
        - http://localhost:5173/callback
        - http://localhost:5173
        - !Sub "https://${UiDistribution.DomainName}/callback"
        - !Sub "${UiCustomDomain}/callback"
      LogoutURLs:
        - http://localhost:5173
        - !Sub "https://${UiDistribution.DomainName}"
      SupportedIdentityProviders:
        - COGNITO

  AdCyberwatchUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Condition: CreateDomainCondition
    Properties:
      Domain: !Ref CognitoDomainPrefix
      UserPoolId: !Ref AdCyberwatchUserPool

  # ----------------------------
  # Cognito Identity Pool (for S3 access via temporary AWS credentials)
  # ----------------------------
  AdCyberwatchIdentityPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      IdentityPoolName: !Sub "${AWS::StackName}-identity-pool"
      AllowUnauthenticatedIdentities: false
      CognitoIdentityProviders:
        - ClientId: !Ref AdCyberwatchUserPoolClient
          ProviderName: !Sub "cognito-idp.${AWS::Region}.amazonaws.com/${AdCyberwatchUserPool}"

  # IAM Role for authenticated users (Cognito Identity)
  AdCyberwatchIdentityPoolRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-identity-pool-role"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: cognito-identity.amazonaws.com
            Action: 'sts:AssumeRoleWithWebIdentity'
            Condition:
              StringEquals:
                'cognito-identity.amazonaws.com:aud': !Ref AdCyberwatchIdentityPool
              ForAnyValue:StringEquals:
                'cognito-identity.amazonaws.com:amr': 'authenticated'
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 's3:PutObject'
                  - 's3:GetObject'
                Resource:
                  - !Sub "${RawBucket.Arn}/*"
              - Effect: Allow
                Action:
                  - 's3:ListBucket'
                Resource:
                  - !GetAtt RawBucket.Arn

  # Attach Identity Pool Role to authenticated users
  AdCyberwatchIdentityPoolRoleAttachment:
    Type: AWS::Cognito::IdentityPoolRoleAttachment
    Properties:
      IdentityPoolId: !Ref AdCyberwatchIdentityPool
      Roles:
        authenticated: !GetAtt AdCyberwatchIdentityPoolRole.Arn

  # ----------------------------
  # HTTP API + JWT Authorizer (Cognito)
  # ----------------------------
  AdCyberwatchHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: prod
      CorsConfiguration:
        AllowOrigins:
          - 'http://localhost:5173'
          - 'http://localhost:5174'
          - !Sub 'https://${UiDistribution.DomainName}'
          - !Ref UiCustomDomain
        AllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        AllowHeaders:
          - Content-Type
          - Authorization
          - X-Amz-Date
          - X-Amz-Security-Token
          - X-Api-Key
        MaxAge: 3600
        AllowCredentials: true
      Auth:
        DefaultAuthorizer: CognitoJwt
        Authorizers:
          CognitoJwt:
            JwtConfiguration:
              issuer: !Sub "https://cognito-idp.${AWS::Region}.amazonaws.com/${AdCyberwatchUserPool}"
              audience:
                - !Ref AdCyberwatchUserPoolClient
            IdentitySource: "$request.header.Authorization"

  # ----------------------------
  # Lambda: API (Node.js) via HTTP API
  # ----------------------------
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-api"
      Runtime: nodejs20.x   # (tu peux garder nodejs24.x si tu veux, mais 20 = POC ultra safe)
      Architectures: [x86_64]
      Handler: src/handlers/api.handler
      CodeUri: ../backend/api-node/
      MemorySize: 256
      Timeout: 30
      Environment:
        Variables:
          MAIN_TABLE_NAME: !Ref AdCyberwatchMainTable
          RAW_BUCKET: !Ref RawBucket
          CURATED_BUCKET: !Ref CuratedBucket
          FRAMEWORKS_BUCKET: !Ref FrameworksBucket
          TENANT_ALIAS: !Ref TenantAlias
          DEFAULT_DATA_ENV: !Ref DefaultDataEnv
          ENABLED_DATA_ENVS: !Ref EnabledDataEnvs
          CORS_ALLOW_ORIGINS: !Sub "http://localhost:5173,http://localhost:5174,https://${UiDistribution.DomainName},${UiCustomDomain}"
      Policies:
        # DynamoDB read/write (simple pour POC)
        - DynamoDBCrudPolicy:
            TableName: !Ref AdCyberwatchMainTable
        # S3 minimal: list + get/put objets dans les 3 buckets
        - Statement:
            - Effect: Allow
              Action:
                - s3:ListBucket
              Resource:
                - !GetAtt RawBucket.Arn
                - !GetAtt CuratedBucket.Arn
                - !GetAtt FrameworksBucket.Arn
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
              Resource:
                - !Sub "${RawBucket.Arn}/*"
                - !Sub "${CuratedBucket.Arn}/*"
                - !Sub "${FrameworksBucket.Arn}/*"
      Events:
        Health:
          Type: HttpApi
          Properties:
            ApiId: !Ref AdCyberwatchHttpApi
            Path: /health
            Method: GET
            Auth:
              Authorizer: NONE
        Me:
          Type: HttpApi
          Properties:
            ApiId: !Ref AdCyberwatchHttpApi
            Path: /me
            Method: GET
        Presign:
          Type: HttpApi
          Properties:
            ApiId: !Ref AdCyberwatchHttpApi
            Path: /uploads/presign
            Method: POST
        DataPresign:
          Type: HttpApi
          Properties:
            ApiId: !Ref AdCyberwatchHttpApi
            Path: /data/{env}/uploads/presign
            Method: POST
        PublicConfig:
          Type: HttpApi
          Properties:
            ApiId: !Ref AdCyberwatchHttpApi
            Path: /public/config
            Method: GET
            Auth:
              Authorizer: NONE
        ControlMe:
          Type: HttpApi
          Properties:
            ApiId: !Ref AdCyberwatchHttpApi
            Path: /control/me
            Method: GET
        ControlEnvironments:
          Type: HttpApi
          Properties:
            ApiId: !Ref AdCyberwatchHttpApi
            Path: /control/environments
            Method: GET

  ApiFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${ApiFunction}"
      RetentionInDays: 7

  IngestOnRawObjectCreatedRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "Trigger ingest on S3 raw Object Created (via EventBridge)"
      EventPattern:
        source:
          - aws.s3
        detail-type:
          - "Object Created"
        detail:
          bucket:
            name:
              - !Ref RawBucket
      Targets:
        - Arn: !GetAtt IngestFunction.Arn
          Id: IngestFunctionTarget

  AllowEventBridgeInvokeIngest:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref IngestFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt IngestOnRawObjectCreatedRule.Arn


  # ----------------------------
  # Lambda: INGEST (Python) déclenchée par S3 raw:ObjectCreated
  # ----------------------------
  IngestFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-ingest"
      Runtime: python3.12
      Architectures: [x86_64]
      Handler: src/handlers/ingest.handler
      CodeUri: ../backend/ingest-python/
      MemorySize: 256
      Timeout: 60
      Environment:
        Variables:
          MAIN_TABLE_NAME: !Ref AdCyberwatchMainTable
          CURATED_BUCKET: !Ref CuratedBucket
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AdCyberwatchMainTable
        - Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
              Resource:
                - !Sub "${RawBucket.Arn}/*"
            - Effect: Allow
              Action:
                - s3:PutObject
              Resource:
                - !Sub "${CuratedBucket.Arn}/*"


  IngestFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${IngestFunction}"
      RetentionInDays: 7

Outputs:
  RawBucketName:
    Value: !Ref RawBucket
  CuratedBucketName:
    Value: !Ref CuratedBucket
  FrameworksBucketName:
    Value: !Ref FrameworksBucket

  UiBucketName:
    Value: !Ref UiBucket

  UiCloudFrontUrl:
    Value: !Sub "https://${UiDistribution.DomainName}"

  UiDistributionId:
    Value: !Ref UiDistribution

  MainTableName:
    Value: !Ref AdCyberwatchMainTable

  UserPoolId:
    Value: !Ref AdCyberwatchUserPool
  UserPoolClientId:
    Value: !Ref AdCyberwatchUserPoolClient
  CognitoHostedUIUrl:
    Description: Cognito Hosted UI Login URL
    Value: !Sub "https://${CognitoDomainPrefix}.auth.${AWS::Region}.amazoncognito.com/login?client_id=${AdCyberwatchUserPoolClient}&response_type=code&redirect_uri=${UiCustomDomain}/callback"

  IdentityPoolId:
    Description: Cognito Identity Pool ID for S3 access
    Value: !Ref AdCyberwatchIdentityPool
  IdentityPoolRoleArn:
    Description: IAM Role ARN for authenticated users via Cognito Identity
    Value: !GetAtt AdCyberwatchIdentityPoolRole.Arn

  HttpApiUrl:
    Value: !Sub "https://${AdCyberwatchHttpApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/prod"

  CognitoDomainPrefix:
    Value: !Ref CognitoDomainPrefix
